import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";

const ubuntuSans = Ubuntu({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntuSans.className} antialiased`}>
        <div className="min-h-screen bg-gray-50">
          <Suspense>
            <Header />
            {children}
            <Footer />
          </Suspense>
        </div>
      </body>
    </html>
  );
}
